#!/bin/bash
# Run the extraction tool.
#

src="${BASH_SOURCE[0]}"
while [[ -L "$src" ]] ; do
    src=$(readlink "$src")
done
scriptdir="$(cd "$(dirname "${src}")" && pwd -P)"

export PYTHONPATH="${scriptdir}"
exec python -m stronghelp.extractor "$@"
